---
- name: Deploy Application to EC2 Instances
  hosts: all
  gather_facts: false

  environment:
    NODE_ENV: devsecops

  tasks:
  - name: Install nodejs 10
    ansible.builtin.package:
      name: "@nodejs:10"
      state: present

  - name: Set NODE_ENV for config
    ansible.builtin.lineinfile:
      state: present
      line: "export NODE_ENV=devsecops"
      insertafter: EOF
      path: /etc/profile

  - name: debug facts stored from controller host
    ansible.builtin.debug:
      var: hostvars[inventory_hostname]['new_pkg_version']
      verbosity: 2

  - name: Extract download
    ansible.builtin.unarchive:
      src: "{{ app_rel_uri }}"
      remote_src: true
      dest: /usr/local/
    register: app_download

  - name: Download JuiceShop config file
    ansible.builtin.get_url:
      url: "{{ app_custom_config }}"
      dest: "{{ node_app_dir }}config/devsecops.yml"
      force: true

  - name: Install Forever
    community.general.npm:
      name: forever
      global: yes
      state: present

  - name: Force NodeJS to bind to IPV4
    replace:
      path: "{{ node_app_dir }}server.js"
      regexp: '^.*\bserver\.listen\b.*$'
      replace: server.listen(process.env.PORT || config.get('server.port'), "0.0.0.0", () => {
      
  - name: Check list of running Node.js apps.
    ansible.builtin.command: forever list
    register: forever_list
    changed_when: false

  - name: Run application
    shell: "NODE_ENV=devsecops forever start app.js"
    args:
      chdir: "{{ node_app_dir }}"
    when: "forever_list.stdout.find('app.js') == -1"


