---
- name: Deploy Hackazon Application to EC2 Instances
  hosts: all
  gather_facts: false
  tasks:
    - name: Pull Hackazon AIO Image
      podman_image:
        name: mutzel/all-in-one-hackazon
        tag: postinstall
        state: present
      tags:
        - app_hackazon_image_pull
        - app
        - devsecops

    - name: Get current running Containers
      ansible.builtin.command:
        cmd: "podman ps --filter name=\"{{ container_name }}\"\n"
      changed_when: false
      register: podman_status
      tags:
        - app_hackazon_pod_status
        - app_hackazon
        - devsecops

    - name: Debug podman status
      ansible.builtin.debug:
        var: podman_status
        verbosity: 2
      tags:
        - debug_app_hackazon_pod_status
        - app_hackazon
        - devsecops

    - name: Stop current Hackazon Container if it running
      ansible.builtin.command:
        cmd: "podman stop {{ container_name }}\n"
      when: podman_status.stdout is search('Up ')
      changed_when: false
      tags:
        - app_hackazon_pod_stop
        - app_hackazon
        - devsecops

    - name: Remove current Hackazon Container if it Exists
      ansible.builtin.command:
        cmd: "podman rm {{ container_name }}\n"
      when: podman_status.stdout is search('Exited ')
      changed_when: false
      tags:
        - app_hackazon_pod_remove
        - app_hackazon
        - devsecops

    - name: Start hackazon AIO Image
      ansible.builtin.command:
        cmd: "podman run --rm --name {{ container_name }} -p 3000:80 -d all-in-one-hackazon:postinstall\n"
      changed_when: false
      tags:
        - app_hackazon_pod_start
        - app_hackazon
        - devsecops
