---
- name: Create new GitHUb release
  hosts: all
  gather_facts: false

  tasks:

                        #   sh """
                        #     git config --replace-all user.name ${env.GITHUB_USERNAME}
                        #     git config --replace-all user.email ${env.GITHUB_USERNAME}
                        #     git config credential.helper store
                        #     echo https://${env.GITHUB_USERNAME}:${env.GITHUB_TOKEN}@github.com >> \$HOME/.git-credentials
                        # """
                        
                        # // Bump the package version.
                        # sh """
                        #     git checkout master --force
                        #     git tag ${newPkgVersion}
                        #     npm --no-git-tag-version version ${newPkgVersion}
                        #     git add .
                        #     git commit -m ${newPkgVersion}
                        #     git push origin master --force
                        #     git push https://github.com/craig-br/juice-shop.git ${newPkgVersion}
                        # """
    - name: create repo dir
      ansible.builtin.tempfile:
        prefix: juiceshop_repo
        state: directory
      register: __juiceshop_tempdir

    - name: Temp dir path
      ansible.builtin.debug:
        var: __juiceshop_tempdir.path

    - name: Download JuiceShop source code
      ansible.builtin.git:
        repo: https://github.com/craig-br/juice-shop.git
        dest: "{{ __juiceshop_tempdir.path }}/juice-shop"
        version: develop

    - name: Configure GitHub repo email
      community.general.git_config:
        name: user.email
        value: "{{ gh_user }}"
        repo: "{{ __juiceshop_tempdir.path }}/juice-shop"

    - name: Configure GitHub repo user
      community.general.git_config:
        name: user.name
        value: "{{ gh_user }}"
        repo: "{{ __juiceshop_tempdir.path }}/juice-shop"

    - name: Configure GitHub credential store
      community.general.git_config:
        name: credential.helper
        value: store
        repo: "{{ __juiceshop_tempdir.path }}/juice-shop"

    - name: Add repo name to store
      ansible.builtin.command: >
        echo https://{{ gh_user }}:{{ gh_password }}@github.com > \$HOME/.git-credentials
      args:
        chdir: "{{ __juiceshop_tempdir.path }}/juice-shop"
      no_log: true

    # - name: Get latest JuiceShop tag
    #   ansible.builtin.shell: >
    #     git tag --list "*10.8.*" | sort --version-sort --reverse | head -n1 | cut -d "-" -f1
    #   args:
    #     chdir: "{{ __juiceshop_tempdir.path }}/juice-shop"
    #   register: __latest_tag

    - name: create new tag
      ansible.builtin.command: "{{ item }}"
      args:
        chdir: "{{ __juiceshop_tempdir.path }}/juice-shop"
      loop:
        - git tag --force {{ tag_name }}
        - npm version --no-git-tag-version --new-version {{ tag_name }}
        - git add .
        - git commit -m " JuiceShop {{ tag_name }}"
        - git push https://{{ gh_user }}:{{ gh_password }}@github.com/craig-br/juice-shop.git {{ tag_name }}


    # - name: Create new release
    #   community.general.github_release:
    #     user: "{{ gh_user }}"
    #     token: "{{ gh_password }}"
    #     repo: https://github.com/craig-br/juice-shop.git
    #     action: create_release
    #     tag: "{{ tag_name }}"
    #     target: "{{ tag_name }}"
    #     name: "JuiceShop Release {{ tag_name }}"
    #   # args:
    #   #   chdir: "{{ __juiceshop_tempdir.path }}/juice-shop"
    #   tags:
    #     - release
    - name: Create new JuiceShop Release
      uri:
        url: "https://api.github.com/repos/{{ gh_user }}/juice-shop/releases"
        method: POST
        headers:
          Authorization: "token {{ gh_password }}"
        body_format: json
        body:
          # '{"target_commitish": "{{ tag_name }}",  "name": "JuiceShop Demo {{ tag_name }}", "draft": false, "prerelease": {{ prerelease | default(false) }}, "accept": "application/vnd.github.v3+json", "tag_name": "{{ tag_name }}"}'
          '{"target_commitish": "{{ target_commitish | default("master") }}",  "name": "JuiceShop Demo {{ tag_name }}", "draft": false, "prerelease": {{ prerelease | default(false) }}, "accept": "application/vnd.github.v3+json", "tag_name": "{{ tag_name }}"}'
        status_code: 201
      register: release_output
      until: release_output.json.errors is not defined
      retries: 60
      delay: 3
      tags:
        - create-release
    - name: remove temp dir
      ansible.builtin.file:
        state: absent
        path: "{{ __juiceshop_tempdir.path }}/juice-shop"
    #     chdir: "{{ __juiceshop_tempdir.path }}/juice-shop"

