---
- name: Deploy Application to EC2 Instances
  hosts: all
  tags:
    - app_deploy
    - webservers
    - devsecops
  environment:
    NODE_ENV: devsecops
  gather_facts: true
  roles:
    - role: geerlingguy.nodejs
      vars:
        nodejs_version: 10.x
  tasks:
    - name: Set NODE_ENV for config
      ansible.builtin.lineinfile:
        state: present
        line: export NODE_ENV=devsecops
        insertafter: EOF
        path: /etc/profile
        mode: "0644"
      tags:
        - node-env

    - name: Debug facts stored from tower host
      ansible.builtin.debug:
        var: hostvars['tower-rhel']['new_pkg_version']
        verbosity: 2
      tags:
        - app-deploy
        - debug-version

    - name: Extract download
      ansible.builtin.unarchive:
        src: "{{ app_rel_uri }}"
        remote_src: true
        dest: /usr/local/
        mode: "0644"
      register: app_download
      tags:
        - extract

    - name: Download JuiceShop config file
      ansible.builtin.get_url:
        url: "{{ app_custom_config }}"
        dest: "{{ node_app_dir }}config/devsecops.yml"
        force: true
      tags:
        - get_config

    - name: Install Forever
      npm:
        name: forever
        global: true
        state: present
      tags:
        - run_app

    - name: Force NodeJS to bind to IPV4
      ansible.builtin.replace:
        path: "{{ node_app_dir }}server.js"
        regexp: ^.*\bserver\.listen\b.*$
        replace: server.listen(process.env.PORT || config.get('server.port'), "0.0.0.0", () => {
        mode: "0644"
      tags:
        - deploy-app
        - ipv4

    - name: Check list of running Node.js apps.
      ansible.builtin.command:
        cmd: forever list
      changed_when: false
      register: forever_list
      tags:
        - run-app

    - name: Run application
      ansible.builtin.command:
        cmd: NODE_ENV=devsecops forever start app.js
      when: forever_list.stdout.find('app.js') == -1
      changed_when: false
      tags:
        - run-app
      args:
        chdir: "{{ node_app_dir }}"
