- name: Start JuiceShop Build
  hosts: all
  gather_facts: false

  tasks:
  - name: Start JuiceShop App Jenkins Job
    ansible.builtin.uri:
      url: "https://juiceshop.demoredhat.com:8080/job/{{ 'JuiceShop App Team' | urlencode }}/build/api/json"
      method: POST
      user: admin
      password: "{{ jenkins_token  }}"
      validate_certs: false
      force_basic_auth: true
      status_code: 201
      return_content: true
    register: __jenkins_job

  - name: Check Job Status
    ansible.builtin.uri:
      url: "https://juiceshop.demoredhat.com:8080/job/{{ 'JuiceShop App Team' | urlencode }}//lastBuild/api/json"
      method: POST
      user: admin
      password: "{{ jenkins_token  }}"
      validate_certs: false
      force_basic_auth: true
      status_code: 200
    register: __jenkins_job_status
    until: not __jenkins_job_status.json.building
    failed_when: __jenkins_job_status.json.result != "SUCCESS"
    retries: 40
    delay: 10

  # - debug:
  #     var: __jenkins_job_status.building
  