---
- name: Push Build to GitHub
  hosts: all
  gather_facts: false
  tags:
    - github-release

  tasks:
  - debug:
      var: hostvars
      
  - name: Create a new release
    community.general.github_release:
      token: "{{ gh_password }}"
      user: "{{ gh_user }}"
      repo: juice-shop
      action: create_release
      # password: "{{ gh_password }}"
      tag: "{{ tag_name }}"
      target: master
      name: "{{ tag_name }}"
      body: "{{ tag_name }} release"
    ignore_errors: true
    register: release
  
  - name: debug
    debug:
      var: release
