---
- name: Deploy Application to EC2 Instances
  hosts: all
  gather_facts: false
  become: true

  environment:
    NODE_ENV: devsecops

  tasks:
  - name: Install packages
    ansible.builtin.dnf:
      name: "@nodejs:14"
      state: present

  - name: Extract download
    ansible.builtin.unarchive:
      src: "{{ app_rel_uri }}"
      remote_src: true
      dest: /usr/local/

  - name: Download JuiceShop config file
    ansible.builtin.get_url:
      url: "{{ app_custom_config }}"
      dest: "{{ node_app_dir }}config/devsecops.yml"

  - name: Install Forever
    community.general.npm:
      name: forever
      global: yes
      state: present

  - name: Force NodeJS to bind to IPV4
    ansible.builtin.replace:
      path: "{{ node_app_dir }}build/server.js"
      regexp: '^.*\bserver\.listen\b.*$'
      replace: server.listen(process.env.PORT || config.get('server.port'), "0.0.0.0", () => {
      
  - name: Check list of running Node.js apps.
    ansible.builtin.command: /usr/local/bin/forever list
    register: forever_list
    changed_when: false

  - name: Run application
    ansible.builtin.command: "/usr/local/bin/forever start build/app.js"
    # ansible.builtin.shell: "NODE_ENV=devsecops /usr/local/bin/forever start build/app.js"
    args:
      chdir: "{{ node_app_dir }}"
    when: "forever_list.stdout.find('app.js') == -1"
