---
- name: Deploy EC2 Web Servers
  hosts: all
  connection: local
  strategy: free
  gather_facts: false

  tasks:
  - name: Deploy Web Servers
    amazon.aws.ec2_instance:
      name: ec2_devsecops
      key_name: "{{ ec2_keyname }}"
      security_group: "{{ ec2_sg_name }}"
      vpc_subnet_id: subnet-0eec001516d14e70b
      instance_type: "{{ ec2_instance_type }}"
      image_id: "{{ ec2_ami }}"
      wait: true
      state: running
      exact_count: "{{ ec2_count }}"
      region: "{{ ec2_region }}"
      network:
        assign_public_ip: true
      tags:
        function: "{{ ec2_webserver_tag }}"
        project: "{{ ec2_project_tag }}"
      wait_timeout: 500
    register: ec2
    until: ec2 is not failed
    retries: 15

  - name: Wait for instances to boot
    ansible.builtin.wait_for:
      host: "{{ ec2.instances[0].public_dns_name }}" 
      port: 22 
      delay: 10  
      timeout: 300
    loop: "{{ ec2.instances }}"
    when: ec2.instances is defined