---
- name: Configure F5 Nodepool
  hosts: all
  connection: local
  gather_facts: false
  become: false

  tasks:
  - name: Gather EC2 facts
    amazon.aws.ec2_instance_info:
      region: "{{ ec2_region }}"
      filters:
        instance-state-name: ["running"]
        "tag:project": "{{ ec2_project_tag }}"
    register: ec2

  - name: Create Facts for F5 configuration
    ansible.builtin.set_fact:
      f5_public_ip: "{{ item.public_ip_address }}"
      f5_private_ip: "{{ item.private_ip_address }}"
      cacheable: true
    when: (item.tags.function == ec2_f5_tag)
    loop: "{{ ec2.instances }}"
  
  # - debug:
  #     var: f5_private_ip
  - name: Create {{ f5_pool_name }} Pool
    f5networks.f5_modules.bigip_pool:
      name: "{{ f5_pool_name }}"
      lb_method: round-robin
      state: "{{ ec2_f5_state }}"
      monitors: ['/Common/http']
      monitor_type: and_list
      provider:
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        server: "{{ f5_public_ip }}"
        server_port: 8443
        validate_certs: "{{ f5_validate_certs }}"
        transport: rest

  - name: Create Pool Members
    f5networks.f5_modules.bigip_pool_member:
      pool: "{{ f5_pool_name }}"
      host: "{{ item.private_ip_address }}"
      port: 3000
      state: "{{ ec2_f5_state }}"
      provider:
        server_port: 8443
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        server: "{{ f5_public_ip }}"
        validate_certs: "{{ f5_validate_certs }}"
        transport: rest
    when: (item.tags.function == ec2_webserver_tag)
    loop: "{{ ec2.instances }}"

  # Deploy with WAF
  - name: Create {{ f5_vs_name }} VS
    f5networks.f5_modules.bigip_virtual_server:
      description: "{{ f5_vs_name }}"
      destination: "{{ f5_private_ip }}"
      name: "{{ f5_vs_name }}"
      pool: "{{ f5_pool_name }}"
      port: "443"
      snat: Automap
      default_persistence_profile: "source_addr"
      all_profiles:
        - http
        - JuiceShop_Client_SSL
        - websecurity
      all_policies:
        - JuiceShop_Policy
      provider:
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        server: "{{ f5_public_ip }}"
        server_port: 8443
        validate_certs: "{{ f5_validate_certs }}"
        transport: rest

  # Deploy without WAF 
  #WEB APP WILL BE HACKED
  # - name: Create {{ f5_vs_name }} VS
  #   f5networks.f5_modules.bigip_virtual_server:
  #     description: "{{ f5_vs_name }}"
  #     destination: "{{ f5_private_ip }}"
  #     name: "{{ f5_vs_name }}"
  #     pool: "{{ f5_pool_name }}"
  #     port: "443"
  #     snat: Automap
  #     default_persistence_profile: "source_addr"
  #     all_profiles:
  #       - http
  #       - JuiceShop_Client_SSL
  #       - websecurity
        # all_policies:
          # - redhat_disable_waf
  #     provider:
  #       user: "{{ f5_user }}"
  #       password: "{{ f5_password }}"
  #       server: "{{ f5_public_ip }}"
  #       server_port: 8443
  #       validate_certs: "{{ f5_validate_certs }}"
  #       transport: rest
