---
## TODO create succes on rc for already registred systems
- name: Install and enable Insights client
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Insights client
      ansible.builtin.package:
        state: present
        name: insights-client
      tags:
        - insights

    - name: Register Guest with Insights
      ansible.builtin.command:
        cmd: >
          insights-client --register
      changed_when: false
      tags:
        - insights
