---
- name: Geerlingguy.git
  src: https://github.com/geerlingguy/ansible-role-git.git
  scm: git

- name: Geerlingguy.ansible
  src: https://github.com/geerlingguy/ansible-role-ansible.git
  scm: git

- name: Geerlingguy.java
  src: https://github.com/geerlingguy/ansible-role-java.git
  scm: git

- name: Openstack.redhat-subscription
  src: https://github.com/openstack/ansible-role-redhat-subscription.git
  scm: git

- name: Geerlingguy.repo-epel
  src: https://github.com/geerlingguy/ansible-role-repo-epel.git
  scm: git

- name: Geerlingguy.nodejs
  src: https://github.com/geerlingguy/ansible-role-nodejs.git
  scm: git
